# Generated by Django 2.2.6 on 2019-11-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_AS', models.CharField(max_length=20, verbose_name='Субъект ГА')),
                ('type_avia', models.CharField(max_length=20, verbose_name='Вид авиации')),
                ('operator', models.CharField(max_length=20, verbose_name='Эксплуатант')),
                ('execut_full_name', models.CharField(max_length=70, verbose_name='ФИО исполнителя')),
                ('execut_post', models.CharField(max_length=70, verbose_name='Должность исполнителя')),
                ('exten_num', models.CharField(max_length=50, verbose_name='Внутренний номер')),
                ('edit_repotr', models.CharField(max_length=50, verbose_name='Редакция отчета')),
                ('prepar_date', models.CharField(max_length=15, verbose_name='Дата составления')),
                ('status_report', models.CharField(max_length=20, verbose_name='Статус отчета')),
                ('contact', models.CharField(max_length=50, verbose_name='Контактная информация')),
                ('zone', models.CharField(max_length=10, verbose_name='Зона')),
                ('type_equipment', models.CharField(max_length=30, verbose_name='Тип техники')),
                ('specialty', models.CharField(max_length=20, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Базовая информация',
                'verbose_name_plural': 'Базовые информации',
            },
        ),
    ]
