# Generated by Django 2.2.6 on 2019-12-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_data', '0002_docx_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docx_save',
            name='docx',
            field=models.FileField(upload_to='docx'),
        ),
    ]
